### ISSUE TITLE
API deprecated ? 

### ISSUE THREAD

**Issue by AbbasTallaq** [woocommerce/wc-api-node#84]
Hi ,
I just wanna know is this plugin got deprecated ? 
because am currently developing my app and this plugin is my app backbone, 
and there's new version of API in Woocommerce seems WC API  isn't pulling the same data in wp-json...
so please let us know

**Comment by saadmomin** [comment]
Not sure man. Facing an issue with this plugin when used with the latest WC version(3.3.1). Unable to make get request on the new WC API version (v1 or v2). It seems to working with the legacy versions but only on GET requests. on POSTs, it gives me invalid signature error. Unable to resolve since 2 days now.

**Comment by AbbasTallaq** [comment]
Hi,
I have updated it my wc to 3.3.1 and i can post fine,
maybe you need to the code again

**Comment by claudiosanches** [comment]
This plugin is no deprecated. But free feel to contribute.
