### ISSUE TITLE
unable to resolve module crypto

### ISSUE THREAD

**Issue by Dwayne01** [woocommerce/wc-api-node#85]
i keep getting this error

> `C:\Users\Anthonia\repo\maxcare\node_modules\woocommerce-api\index.js`: Module does not exist in the module map or in these directories:   C:\Users\Anthonia\repo\maxcare\node_modules

this is my code
`var WooCommerceAPI = require('woocommerce-api');

var Api = new WooCommerceAPI({
    url: 'http://localhost/wordpress/',
    consumerKey: 'ck_131767da20304ce21b86f593273c989ac2cffa0b',
    consumerSecret: 'cs_416f6ccbf56bb77f36553acbe77bbae619ab4571',
    version: 'v3'
});
`

please what am i doing wrong?

**Comment by SMKH-PRO** [comment]
No Solution Yet?
I am also getting this error on react-native !!, i tried to install crypto but this package is deprecated..

**Comment by ertejaspatel** [comment]
Any updates on this one? I am also finding similar issue. 
Module `crypto` does not exist in the Haste module map

**Comment by LFMAKER** [comment]
No solution yet? pls

**Comment by rurigk** [comment]
https://nodejs.org/api/crypto.html#crypto_determining_if_crypto_support_is_unavailable
https://stackoverflow.com/questions/29836434/requiring-unknown-module-crypto-in-react-native-environment

**Comment by FarriiJutt** [comment]
The issue is that the Webpack config generated in this Angular project configured node to have the modules not loaded. Therefore, the fix is to modify the parameters to include these missing modules.

On every update of your node packages, edit this file:

`node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js`

> node: false

to

> node: { crypto: true, stream: true, fs: 'empty', net: 'empty', tls: 'empty'}

Note that if you upgrade your packages, most likely, you have to repeat this process again. You can build an automated script like below:

Update `package.json` and add this line into the `scripts` section.

> "scripts": {
>   ...
>   "postinstall": "node patch-webpack.js"
>   ...
> }
> 

Then create the patch script `patch-webpack.js`

const fs = require('fs');
const f = 'node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js';
 

> fs.readFile(f, 'utf8', function (err,data) {
>   if (err) {
>     return console.log(err);
>   }
>   let result = data.replace(/node: false/g, "node: {crypto: true, stream: true, fs: 'empty', net: 'empty'}");
>  
>   fs.writeFile(f, result, 'utf8', function (err) {
>     if (err) return console.log(err);
>   });
> });

That’s it! Enjoy Coding!

**Comment by IntelliJAbhishek** [comment]
@SMKH-PRO use this library https://www.npmjs.com/package/react-native-wc-api

**Comment by claudiosanches** [comment]
This library is now deprecated, you should try https://github.com/woocommerce/woocommerce-rest-api-js-lib
